version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8081:8080"
    command: sh -c "cd /app/ && npm install && npm run dev"